# Generated by Django 2.2.13 on 2022-12-08 09:11

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('JobId', models.CharField(default=server.models.unique_job_id, max_length=20, unique=True)),
                ('Email', models.EmailField(max_length=50)),
                ('Epochs', models.IntegerField(default=500)),
                ('BatchSize', models.IntegerField(default=1)),
                ('Encoder', models.CharField(default='mlp', max_length=10)),
                ('Decoder', models.CharField(default='rnn', max_length=10)),
                ('Lr', models.FloatField(default=0.0005)),
                ('JobStatus', models.BooleanField(default=False)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('TrajFilePath', models.CharField(max_length=500, null=True, unique=True)),
                ('StrucFilePath', models.CharField(max_length=500, null=True, unique=True)),
                ('DomainImg', models.ImageField(null=True, upload_to='')),
                ('ProbsImg', models.ImageField(null=True, upload_to='')),
                ('PathTxt', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StructureFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StructureFile', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TrajectoryFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrajectoryFile', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
