# Generated by Django 2.2.13 on 2022-12-16 14:05

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('JobId', models.CharField(default=server.models.unique_job_id, max_length=20)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Epochs', models.IntegerField(blank=True, default=500, null=True)),
                ('Start', models.IntegerField(blank=True, default=1, null=True)),
                ('End', models.IntegerField(blank=True, default=56, null=True)),
                ('BatchSize', models.IntegerField(blank=True, default=1, null=True)),
                ('Encoder', models.CharField(default='mlp', max_length=10)),
                ('EncoderDropout', models.IntegerField(default=0)),
                ('EncoderHidden', models.IntegerField(default=256)),
                ('Decoder', models.CharField(default='rnn', max_length=10)),
                ('DecoderDropout', models.IntegerField(default=0)),
                ('DecoderHidden', models.IntegerField(default=256)),
                ('Lr', models.FloatField(default=0.0005)),
                ('LrDecay', models.IntegerField(default=200)),
                ('TimestepSize', models.IntegerField(default=50)),
                ('TrainInterval', models.IntegerField(default=60)),
                ('ValidateInterval', models.IntegerField(default=80)),
                ('TestInterval', models.IntegerField(default=100)),
                ('Var', models.FloatField(default=5e-05)),
                ('Gamma', models.FloatField(default=0.5)),
                ('Domain', models.CharField(default='A_0_40,B_41_70,C_71_76', max_length=10)),
                ('SourceNode', models.IntegerField(default=46)),
                ('TargetNode', models.IntegerField(default=61)),
                ('JobStatus', models.BooleanField(default=False)),
                ('NumResidues', models.IntegerField(default=0)),
                ('NumFrames', models.IntegerField(default=0)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('TrajFilePath', models.CharField(max_length=500, null=True, unique=True)),
                ('StrucFilePath', models.CharField(blank=True, max_length=500, null=True)),
                ('DomainImg', models.ImageField(null=True, upload_to='')),
                ('ProbsImg', models.ImageField(null=True, upload_to='')),
                ('PathTxt', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StructureFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StructureFile', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TrajectoryFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrajectoryFile', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
