# Generated by Django 2.2.13 on 2022-12-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='JobId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='TrajFilePath',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
