# Generated by Django 2.2.13 on 2022-12-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20221216_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='Domain',
            field=models.CharField(default='A_0_40,B_41_70,C_71_76', max_length=100),
        ),
    ]
