# Generated by Django 2.2.13 on 2022-12-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20221208_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='StrucFilePath',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
