# Generated by Django 2.2.13 on 2022-12-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20221216_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='DistThreshold',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='Seed',
            field=models.IntegerField(blank=True, default=42, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='VisualThreshold',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='DecoderDropout',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='EncoderDropout',
            field=models.FloatField(default=0.0),
        ),
    ]
