# Generated by Django 2.2.13 on 2022-12-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20221208_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='JobId',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
