# Generated by Django 2.2.13 on 2022-12-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20221217_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='DistThreshold',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='VisualThreshold',
            field=models.FloatField(default=0.6),
        ),
    ]
