# Generated by Django 2.2.13 on 2022-12-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20221217_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='DistThreshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='SourceNode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='TargetNode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
